### ISSUE TITLE
ZeroDivisionError when generating descriptions for novel images

### ISSUE THREAD

**Issue by evanmiltenburg** [elliottd/GroundedTranslation#15]
Just pulled the most recent commits to get beam search to work, and now I have this bug.

```
ubuntu@emiels_machine:~/GroundedTranslation$ python generate.py --model_checkpoints checkpoints/fixed_seed-eng256mlm --dataset /home/ubuntu/image_features --without_scores
INFO:data_generator:Initialising data generator
INFO:data_generator:Train/val dataset: /home/ubuntu/image_features
INFO:data_generator:Input gold descriptions
INFO:__main__:Best checkpoint: checkpoints/fixed_seed-eng256mlm/050-11012016-193333
INFO:data_generator:Initialising vocabulary from pre-defined model
INFO:data_generator:Max seq length 29, setting max_seq_len to 31
INFO:data_generator:Split sizes {'test': 0, 'train': 0, 'val': 1501}
INFO:data_generator:Number of words 0 -> 1764
Traceback (most recent call last):
  File "generate.py", line 479, in <module>
    w.generationModel()
  File "generate.py", line 64, in generationModel
    self.data_gen.set_vocabulary(self.args.checkpoint)
  File "/home/ubuntu/GroundedTranslation/data_generator.py", line 579, in set_vocabulary
    self.corpus_statistics()
  File "/home/ubuntu/GroundedTranslation/data_generator.py", line 681, in corpus_statistics
    actual_len, true_len, 100 * float(actual_len)/true_len)
ZeroDivisionError: float division by zero
```

**Comment by evanmiltenburg** [comment]
Easiest solution I can think of is to switch off corpus statistics. Shall I implement this with an additional flag?

**Comment by elliottd** [comment]
I think we need to rewrite the way data_generator works when the code is being run in prediction mode from the generate.py script.

**Comment by evanmiltenburg** [comment]
Yes, the train/val/test distinction is irrelevant for this use case, but it pops up everywhere.

**Comment by evanmiltenburg** [comment]
Ok, so what about removing `self.corpus_statistics()` from `set_vocabulary` in `data_generator` and adding `self.data_gen.corpus_statistics()` to `generationModel`? That might be more intuitive, because we want to have multiple modes for the model anyway: 'prediction mode' and 'evaluation mode'. If the default is evaluation mode, there could be a flag for prediction mode, which disables the statistics.
